// <auto-generated />
namespace FinalProject.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PostDavidedits : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostDavidedits));
        
        string IMigrationMetadata.Id
        {
            get { return "202108281756286_Post David edits"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
